### ISSUE TITLE
CREATE ROUTES FOR NAVBAR ELEMENTS

### ISSUE THREAD

**Issue by DenisKantic** [DenisKantic/ADOPT_PETS_NIRINA_COLLAB#3]
To complete this task you need to create routes for all elements in navbar, using router in react.

**Comment by DenisKantic** [comment]
Finished with my part, now it's your turn. @Bego96

**Comment by Bego96** [comment]
Finnished Router for current available components

**Comment by DenisKantic** [comment]
Great work!
